version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: D:\Python_ML\Artizence_Task\V2\resume_evaluator\backend\DockerFile
    container_name: resume_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend

  frontend:
    build:
      context: .
      dockerfile: D:\Python_ML\Artizence_Task\V2\resume_evaluator\frontend\DockerFile
    container_name: resume_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - .:/app
